#!/usr/bin/env php
<?php
require_once __DIR__ . '/../../vendor/autoload.php';
use function PhpProject45\Cli\sayName;
use function PhpProject45\Engine\games_Question;
use function PhpProject45\Engine\games_Condition;
use function PhpProject45\Engine\gamesPrime;
use function cli\prompt;

$name = sayName();//определяем имя игрока
$question = "Answer \"yes\" if given number is prime. Otherwise answer \"no\".\n"; // вопрос для данной игры

function game($name, $question)
{
    games_Question($question);
    $count = 0;
    while ($count < 3) {
        $num1 = rand(1, 20);
        $trueAnswer = gamesPrime($num1);
        print_r("Question: $num1\n");
        $answer = prompt('Your answer');
        $condition = $answer === $trueAnswer; //условие при котором выигрыш
        $count = games_Condition($condition, $count, $answer, $trueAnswer, $name);//функция осуществляющая проверку
        if ($count === false) {
            break;
        }
        if ($count === 3) {
            print_r("Congratulations, $name!\n");
        }
    }
}

game($name,$question);