#!/usr/bin/env php
<?php
require_once __DIR__ . '/../../vendor/autoload.php';

use function PhpProject45\Cli\sayName;
use function PhpProject45\Engine\games_Question;
use function PhpProject45\Engine\games_Condition;
use function PhpProject45\Engine\games_Progress;
use function cli\prompt;

$name = sayName();//определяем имя игрока
$question = "What number is missing in the progression?\n"; // вопрос для данной игры

function game($name, $question)
{
    games_Question($question);
    $count = 0;
    while ($count < 3) {
        $arr = games_Progress();
        $hide = rand(0, 9);
        $trueAnswer = (string) $arr[$hide];
        $arr[$hide] = "..";
        $str = implode(' ', $arr);
        print_r("Question: $str\n");
        $answer = prompt('Your answer');
        $condition = $answer === $trueAnswer; //условие при котором выигрыш
        $count = games_Condition($condition, $count, $answer, $trueAnswer, $name);//функция осуществляющая проверку
    }
    print_r("Congratulations, $name!\n");
}

game($name, $question);